-- DROP TABLE RECIPE IF EXISTS;
-- DROP TABLE DOCTOR IF EXISTS;
-- DROP TABLE PATIENT IF EXISTS;

CREATE TABLE IF NOT EXISTS DOCTOR
(
  ID bigint PRIMARY KEY NOT NULL IDENTITY,
  FIRSTNAME varchar(256) NOT NULL,
  LASTNAME varchar(256) NOT NULL,
  PATRONYMIC varchar(256),
  SPECIALIZATION varchar(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS PATIENT
(
  ID bigint PRIMARY KEY NOT NULL IDENTITY,
  FIRSTNAME varchar(256) NOT NULL,
  LASTNAME varchar(256) NOT NULL,
  PATRONYMIC varchar(256),
  PHONE varchar(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS RECIPE
(
  ID          BIGINT PRIMARY KEY               NOT NULL IDENTITY,
  DESCRIPTION VARCHAR(1024)                    NOT NULL,
  PATIENT_ID  BIGINT,
  DOCTOR_ID   BIGINT,
  CREATED     TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
  PRIORITY    VARCHAR(256)                     NOT NULL,
  CONSTRAINT RECIPE_PATIENT_ID_FK FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT (ID)
    ON UPDATE CASCADE ON DELETE NO ACTION,
  CONSTRAINT RECIPE_DOCTOR_ID_FK FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR (ID)
    ON UPDATE CASCADE ON DELETE NO ACTION
);
